- src/m4.js
```setTranslation``` did not define a ```v``` param and did not keep data from the input matrix ```a```
Also adjusted jsdoc to add ```dst``` param
> fixed m4.setTranslation

- src/twgl.js
Hi Greg,
My js2-mode for emacs highlights several variable reference errors.
These are usually typos, referencing undefined variables, where another one was obviously intended.
In one case I added 'var' to make a variable local.
I ran all the examples to make sure I didn't break anything.
> Fixed several variable name errors.

- src/twgl.js
Many browsers support the OES_element_index_uint extension, permitting
drawElements to operate using 32-bit element indexes. In
createBufferInfoFromArrays, when creating the buffer for indices,
record the element type of the indices elements in a new property,
bufferInfo.elementType. Later, when calling  drawElements, use the value
of bufferInfo.elementType.
If the calling program needs to use 32 bit int indexes, it should call
gl.getExtension("OES_element_index_uint"); if the extension is available,
then it can pass a Unit32Array in the indices property.
var arrays = {
position: [-1, -1, 0, 1, -1, 0, -1, 1, 0, 1, 1, 0],
indices:  new Uint32Array([ 0, 1, 2, 2, 1, 3])
};
var bufferInfo = twgl.createBufferInfoFromArrays(gl, arrays);
> Permit passing indices of type Uint32Array in createBufferInfoFromArrays

- src/twgl.js
The signature of `createTexture` callback is `function(err, tex, img)`
While the plural version, `createTextures` is  `function (err, textureOptions)` which is inconsistent.
So I changed it to `function(error, texs, imgs)`.
> change the callback in createTextures to be same as createTexture

- src/draw.js
Currently the drawObjectList function will always default to `object.type = gl.TRIANGLES` when setting type to `gl.POINTS` because `gl.POINTS` is `0` and therefore always falsy.
The changes in this PR will check if `object.type` is defined at all and default to `gl.TRIANGLES` only when `object.type` is `undefined`.
PS: Thanks for the great work!
> fix drawObjectList when type is gl.POINTS

- examples/3d-texture-volume-no-buffers.html
- examples/3d-texture-volume.html
Fix 3D texture examples on latest Firefox and Chrome.
```
Uncaught TypeError: Failed to execute 'texSubImage3D' on 'WebGL2RenderingContext': 11 arguments required, but only 8 present.
at drawCircleLow (3d-texture-volume.html:132)
at drawCircle (3d-texture-volume.html:147)
at main (3d-texture-volume.html:166)
at 3d-texture-volume.html:371
```
> Fix calls to gl.texSubImage3D.

- src/twgl.js
By this way, can easily reduce resolution when need optimize in low-power machine.
> allow resizeCanvasToDisplaySize reduce the resolution

- src/attributes.js
In the first example of https://twgljs.org/docs/module-twgl.html#.createBufferInfoFromArrays , no `type`argument is given. Also, the code works fine without it, even when using js arrays.
> Fixed documentation.

- src/m4.js
The arguments `top` and `bottom` were reversed in the documentation.
> Fixed the documented argument ordering of `ortho`.

- src/m4.js
Fix missing optional tag on dst parameter in definition files for m4.transformPoint and m4.transformDirection.
> Doc fixes for optional dst parameter

- src/programs.js
Support for constant attributes was incomplete, only vec4 was supported.
This patch adds support for float, vec2, and vec3 attributes.
Also, an error is thrown for unsupported array/vector lengths.
> Adds support for float, vec2/3 constant attributes

- src/draw.js
In this loop, there is no guarantee that `lastUsedBufferInfo` is not `null` at the time that this conditional is reached. Consequently, you can find yourself in a situation where calling this method throws an uncaught exception.
I'm running into this when loading ~60 images into memory using `twgl.createTextures` and then calling this method after the images are loaded. Sometimes this method errors when I am doing this, perhaps due to some race condition? I'm not sure the specific cause, but this change makes this function type safe, and ensures the uncaught exception will never happen.
> Fixes uncaught TypeError in certain conditions

- src/primitives.js
The zero area rings between the cone/cylinder faces are intended to separate the normal and uv coordinates of each faces. But the triangles of these rings are unnecessary and should therefore be removed.
> Patch for cone and cylinder primitives: remove the useless triangles

- src/framebuffers.js
It seems to be a typo. As I can see, `texTarget` is some legacy property and unsupported now
> Fix framebuffer target value

- package.json
By doing this it would be possible to find your package with this keywords ...
> add `util` and `helper` to keywords list

- src/framebuffers.js
In TypeScript 4.3, `WebGLObject` was dropped from `lib.dom.d.ts`.
This commit replaces uses of `WebGLObject` with `WebGLRenderbuffer|WebGLTexture`.
Based on reading TWGL's `createFramebufferInfo(...)` these two are the
only possible object types for attachments in `FramebufferInfo`.
Relevant TypeScript changes:
[Justification for removal of `WebGLObject`](https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/991)
[Removal of `WebGLObject`](https://github.com/microsoft/TypeScript/pull/44423)
> fix: make compatible with TypeScript 4.3

- src/programs.js
- test/tests/program-tests.js
- test/webgl.js
This is just an experiement. I haven't decided if this is going to be added or not
Trying out, given uniforms like this.
```
struct Extra {
float f;
vec4 v4;
vec3 v3;
};
struct Light {
float intensity;
vec4 color;
float nearFar[2];
Extra extra[2];
};
uniform Light lights[2];
```
You can set them like this
```
twgl.setUniformTree(programInfo, {
lights:[
{ intensity: 1.5, color: [1, 0, 0, 1], nearFar: [0.1, 1.0], extra: [ f: 0.1, v4: [1.2, 3.4, 1.2, 1.4], v3: [0, 1, 2], },
{ intensity: 2.3, color: [0, 0, 1, 1], nearFar: [0.1, 1.0], extra: [ f: 0.7, v4: [3.1, 7.9, 0.6, 5.8], v3: [4, 5, 6], },
],
});
```
> Experiment with uniform-tree support

- src/vertex-arrays.js
`createVAOAndSetAttributes` and `createVAOFromBufferInfo` were missing return type `WebGLVertexArrayObject | null`
> fixed missing return types in `vertex-arrays.js`

- src/primitives.js
There doesn't seem to be a function called `createPlaneArrays`.  I think it should be `createPlaneVertices` instead.
> Fix a comment in primitives.js

- src/attributes.js
- src/programs.js
Previously, if the divisor property was absent, the gl.vertexAttribDivisor call would be omitted, which caused the divisor value to be inherited from the
previous program.
With this change, an absent divisor causes an explicit call to gl.vertexAttribDivisor with parameter zero.
Note this is a breaking change if people have been deliberately or accidentally carrying divisor values forward from one program to the next.
> Always call vertexAttribDivisor

- src/helper.js
- test/index.js
- test/tests/helper-tests.js
Resolves https://github.com/greggman/twgl.js/issues/125
I ran into the `instanceof` error when trying to use twgl with [react-new-window](https://github.com/rmariuzzo/react-new-window). However, the bug occurs with any multi-realm project, it's not specific to that library. This behavior of `instanceof` is described in its [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_realms).
I have successfully tested this with my project.
> Fix 'instanceof' bug

- src/attributes.js
Have been having to use `// @ts-ignore` in my project to use this property, but it looks like it's valid: it's consumed in the `createAttribsFromArray` function here: https://github.com/greggman/twgl.js/blob/2bd840a29c88050efa3dae9e2cc676bd7ca666be/src/attributes.js#L432
> Add missing `drawType` property to `FullArraySpec`
